version: '2'
services:
  mongo:
    image: "mongo:latest"
    hostname: "MongoDB"
    container_name: "oop-mongodb"
    environment:
      - "MONGO_DATA_DIR=/data/db"
      - "MONGO_LOG_DIR=/data/logs"
    volumes:
      - "./mongo/data/db:/data/db"
      - "./mongo/data/logs:/data/logs"
    ports:
        - "27017:27017"
    command: "mongod --smallfiles" 
  tomcat:
    image: "tomcat"
    hostname: "OOPTomcat"
    container_name: "oop-tomcat"
    volumes:
      - "./bin/artifacts/VizDizTree/:/usr/local/tomcat/webapps/"
    ports:
      - "8080:8080"